server.port: 9999

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: PUBLIC
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
    username: user
    password: password
    url: jdbc:h2:mem:test?SCHEMA=PUBLIC

